"""new fields user

Revision ID: 703a831cd1fe
Revises: da93c4e204e5
Create Date: 2019-02-01 10:34:26.194472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703a831cd1fe'
down_revision = 'da93c4e204e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
